#!/usr/bin/sh
# == MONTHLY BACKUP =============================

vars() {
  backup_dir=$HOME/.local/backup/monthly
}

check_dirs() {
  if [ ! -d "$BACKUP_DIR" ]; then
    mkdir -p "$BACKUP_DIR"
  fi
}

# TODO create variable for the directory to be backed up
# The following tar command will create a compressed archive of the ~/.config/ directory in the ~/.local/backup/weekly/ directory. 
# TODO Check if backup directory exists, if not, create it.
tar -zcf $HOME/.local/backup/monthly/$(date +%Y%m%d)-backup.tar.gz $HOME/.config/
# The find command will remove all montly backups that are older than 365 days or 1 year.
find $HOME/.local/backup/monthly/* -mtime +365 -delete
