#!/usr/bin/sh
# == WEEKLY BACKUP ==============================

# TODO create variable for the backup storage directory
# TODO create variable for the directory to be backed up
# The following tar command will create a compressed archive of the ~/.config/ directory in the ~/.local/backup/weekly/ directory. 
# TODO Check if backup directory exists, if not, create it.
tar -zcf $HOME/.local/backup/weekly/$(date +%Y%m%d)-backup.tar.gz $HOME/.config/
# The find command will remove all weekly backups that are older than 31 days or 1 month.
find $HOME/.local/backup/weekly/* -mtime +31 -delete
