#!/usr/bin/sh
# ==  BACKUP DIRECTORY  ======================================
# Description: 
#   Creates a backup of the specified directory to a specified location
# Author: chris4727
# Dependancies:
#   rsync

vars() {
# Create backup_dir variable for the directory to be backed up from user input arg 1
  backup_dir=$1
# Create source_dir variable for the directory to copy the backup from user input arg 2
  source_dir=$2
# Create backup directory name with date
  backup_name=$(date +"%Y%m%d")-"$source_dir"-backup
# Create full path for backup directory
  full_backup_dir=$backup_dir/$backup_name
}

echo_vars() {
  echo backup_dir $backup_dir
# Create source_dir variable for the directory to copy the backup from user input arg 2
  echo source_dir $source_dir
# Create backup directory name with date
  echo backup_name $backup_name
# Create full path for backup directory
  echo full_backup_dir $full_backup_dir
}

#check_dirs() {
## TODO check if backup_dir and source_dir exist
#}

backup() {
   rsync -rvhaP --progress "$source_dir" "$full_backup_dir"
}

main() {
  vars "$@"
  echo_vars
  #check_dirs
  #backup
}

main
