#!/usr/bin/sh
# == MONTHLY BACKUP =============================

vars() {
  backup_dir=$HOME/.local/backup/monthly
# TODO create variable for the directory to be backed up created from
# user input
}

check_dirs() {
  if [ ! -d "$BACKUP_DIR" ]; then
    mkdir -p "$BACKUP_DIR"
  fi
}

backup() {
# The following tar command will create a compressed archive of the ~/.config/ directory in the ~/.local/backup/weekly/ directory. 
  tar -zcf $HOME/.local/backup/monthly/$(date +%Y%m%d)-backup.tar.gz $HOME/.config/
# TODO Create rsync command to backup the backup_dir to source_dir
# The find command will remove all montly backups that are older than 365 days or 1 year.
  find $HOME/.local/backup/monthly/* -mtime +365 -delete
}
