#!/usr/bin/sh
# ==  backup_dir  ======================================
# Description: 
#   Creates a backup of the specified directory to a specified location
# Author: chris4727
# Dependancies:
#   rsync


