#! /usr/bin/bash 
# ==  CONVERT VID TO H264 ======================
# Author: chris4727
# Dependencies:
# - ffmpeg


vars() {
  input_file="$1"
  filename=${1%%.*}
  height="$2"
  red="\033[0;31m"
  blu="\033[0;34m"
  grn="\033[0;32m"
  prp="\033[0;35m"
  nc="\033[0m" # No Color
}

echo_vars() {
  printf "$input_file\n"
  printf "$filename\n"
  printf "$height\n"
}

check_args() {
  if [ $# -ne 2 ]; then
    printf "${red}Error:${nc} This script expects two arguments, <input-video> and <output height in pixels> (1080, 720, 480).\n"
    printf "${grn}Usage:${nc} 'vid_to_h264 input.mp4 480'\n"
    exit 1
  fi
}

convert_vid() {
    # Convert to h264 8-bit
  printf "${blu}:: ${nc}Converting ${prp}$input_file${nc} to $height, 8-bit h264\n"
    # Only output errors 
    # h264
    # Compression. 0 Best quality, largest file
    # Sets pixel height keeping aspect ratio
    # 8-bit for max compatibility
  ffmpeg -v error -i "$input_file" -c:v libx264 -crf 20 -vf scale=-2:"$height",format=yuv420p -c:a copy ${filename}-h264.mp4
    #&
}

main() {
  vars "$@"
  #echo_vars
  check_args "$@"
  convert_vid
  printf "${grn}==>${nc} Conversion completed.\n"
}

main "$@"


