#!/usr/bin/bash
# ==  YTDL AUDIO  ===============================
# Author: chris4727
# Downloads audio file
# Dependencies:
# - yt-dlp


vars() {
  input_url="$1"
  output_dir="$HOME/Music/ytdlp"
  red="\033[0;31m"
  blu="\033[0;34m"
  grn="\033[0;32m"
  prp="\033[0;35m"
  nc="\033[0m" # No Color
}

check_dep() {
  if ! command -v "yt-dlp" &> /dev/null
  then
    printf "${red}Error:${nc} yt-dlp is not installed.\n"
    exit 1
  fi
}

echo_vars() {
  printf "$input_url\n"
  printf "$output_dir\n"
}

check_args() {
  if [ $# -ne 1 ]; then
    printf "${red}Error:${nc} This script expects one argument <input-url>\n"
    printf "${grn}Usage:${nc} ytdla <url.com>\n"
    exit 1
  fi
}

get_audio() {
  printf "${blu}:: ${nc}Downloading ${prp}$input_url${nc} into $output_dir\n"
  yt-dlp -x "$input_url" --audio-format m4a --audio-quality 0 -o "%(title)s/%(title)s.%(ext)s" --write-thumbnail --convert-thumbnails jpg -P "$output_dir"
  # Match jellyfin music naming convention
  # https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#output-template-examples
  printf "${grn}==>${nc} Download completed.\n"
}

main() {
  vars "$@"
  check_dep
  #echo_vars
  check_args "$@"
  get_audio
}

main "$@"


